# helpers/init_wizard.py
"""
Interactive first-run setup wizard (python main.py --init).

Guides the user through:
  Step 1 — Data provider + optional Polygon API key
  Step 2 — Capital & backtest dates
  Step 3 — What to test (single symbol / portfolio)
  Step 4 — Write config_starter.py (and optionally .env)

Design constraints
------------------
- stdlib only: sys, os, pathlib, textwrap, datetime — no pip installs.
- No network calls.
- Nothing written to disk without explicit user confirmation.
- Will not overwrite an existing config.py.
"""

from __future__ import annotations

import os
import re
import sys
import textwrap
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Colour / formatting helpers
# ---------------------------------------------------------------------------

# Disable ANSI on Windows cmd / non-TTY environments.
_USE_COLOR: bool = sys.stdout.isatty() and os.name != "nt"


def _ansi(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _USE_COLOR else text


def bold(text: str) -> str:
    return _ansi("1", text)


def green(text: str) -> str:
    return _ansi("32", text)


def yellow(text: str) -> str:
    return _ansi("33", text)


def cyan(text: str) -> str:
    return _ansi("36", text)


def red(text: str) -> str:
    return _ansi("31", text)


# ---------------------------------------------------------------------------
# Low-level prompt helpers
# ---------------------------------------------------------------------------

def _section(title: str) -> None:
    """Print a bold section separator."""
    width = 60
    print()
    print(bold("=" * width))
    print(bold(f"  {title}"))
    print(bold("=" * width))


def _ask(prompt: str, choices: list[str] | None = None, default: str = "") -> str:
    """
    Prompt the user for input, validate against *choices* if supplied.

    Returns the lowercase-stripped answer (or *default* on empty Enter).
    Exits cleanly on Ctrl-C / EOF.
    """
    choice_hint = f"[{'/'.join(choices)}]" if choices else ""
    default_hint = f" (default: {default})" if default else ""
    full_prompt = f"  {prompt} {choice_hint}{default_hint}: "

    while True:
        try:
            raw = input(full_prompt).strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            sys.exit(0)

        answer = raw or default.lower()

        if choices and answer not in [c.lower() for c in choices]:
            print(red(f"  Please enter one of: {', '.join(choices)}"))
            continue

        return answer


def _confirm(prompt: str) -> bool:
    """Prompt for y/n. Returns True for 'y'."""
    return _ask(prompt, choices=["y", "n"], default="y") == "y"


# ---------------------------------------------------------------------------
# Config builder
# ---------------------------------------------------------------------------

def _build_config(
    provider: str,
    capital: float,
    start: str,
    end_expr: str,
    mode: str,
    symbols_or_portfolio: object,
) -> str:
    """
    Return the full text of config_starter.py.

    Parameters
    ----------
    provider             : one of 'yahoo', 'csv', 'polygon', 'norgate'
    capital              : initial capital as a float
    start                : start_date string e.g. '2010-01-01'
    end_expr             : Python expression for end_date, e.g.
                           'datetime.now().strftime("%Y-%m-%d")'
    mode                 : 'single' or 'portfolio'
    symbols_or_portfolio : list[str] for single; dict for portfolio
    """
    # Build symbols / portfolios blocks
    # Use explicit double-quote formatting so ast.parse() can validate
    # the output and tests can assert on '"key": "value"' patterns.
    if mode == "single":
        symbols_line = f'    "symbols_to_test": {symbols_or_portfolio!r},'
        portfolios_block = (
            '"portfolios": {\n'
            '        # Single-asset mode — symbols driven by symbols_to_test above.\n'
            '    },'
        )
    else:
        symbols_line = '    "symbols_to_test": [],'
        portfolios_repr = repr(symbols_or_portfolio)
        portfolios_block = f'"portfolios": {portfolios_repr},'

    # Polygon-specific notes
    polygon_note = (
        '    # Set POLYGON_API_KEY in your .env file (see .env.example).\n'
        if provider == "polygon"
        else ""
    )

    # Template string starts at column 0 so textwrap.dedent is not needed
    # and ast.parse() always succeeds on the output.
    config_text = (
f'# config_starter.py — generated by python main.py --init\n'
f'# Rename to config.py to activate, or copy sections you need into your existing config.py.\n'
f'\n'
f'from datetime import datetime\n'
f'\n'
f'CONFIG = {{\n'
f'    # ============================================================\n'
f'    # SECTION 1: DATA PROVIDER\n'
f'    # ============================================================\n'
f'    # Options: "polygon", "norgate", "yahoo", "csv"\n'
f'    "data_provider": "{provider}",\n'
f'{polygon_note}'
f'\n'
f'    # --- CSV Data Directory (only used when data_provider = "csv") ---\n'
f'    "csv_data_dir": "csv_data",\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 2: BACKTEST PERIOD & CAPITAL\n'
f'    # ============================================================\n'
f'    "start_date": "{start}",\n'
f'    "end_date": {end_expr},\n'
f'\n'
f'    # --- Initial Capital (USD, no commas) ---\n'
f'    "initial_capital": {capital},\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 3: TIMEFRAME SERIES\n'
f'    # ============================================================\n'
f'    "timeframe": "D",  # Daily\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 4: PRICE ADJUSTMENT & BENCHMARKS\n'
f'    # ============================================================\n'
f'    "price_adjustment": "total_return",\n'
f'    "benchmark_symbol": "SPY",\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 5: FILE OUTPUT\n'
f'    # ============================================================\n'
f'    "save_individual_trades": True,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 6: BACKTEST FILTERING SETTINGS\n'
f'    # ============================================================\n'
f'    "mc_score_min_to_show_in_summary": -9999,\n'
f'    "min_pandl_to_show_in_summary": -9999,\n'
f'    "max_acceptable_drawdown": 1.0,\n'
f'    "min_performance_vs_spy": -9999,\n'
f'    "min_performance_vs_qqq": -9999,\n'
f'    "save_only_filtered_trades": False,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 7: PORTFOLIO SETTINGS\n'
f'    # ============================================================\n'
f'    {symbols_line}\n'
f'    "min_bars_required": 250,\n'
f'    {portfolios_block}\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 8: ALLOCATION, EXECUTION FILTERING\n'
f'    # ============================================================\n'
f'    "allocation_per_trade": 0.10,\n'
f'    "max_pct_adv": 0.05,\n'
f'    "execution_time": "open",\n'
f'    "roc_thresholds": [0.0, 0.5],\n'
f'    "show_qqq_losers": False,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 9: STOP LOSS SETTINGS\n'
f'    # ============================================================\n'
f'    "stop_loss_configs": [\n'
f'        {{"type": "none"}},\n'
f'    ],\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 10: MONTE CARLO SETTINGS\n'
f'    # ============================================================\n'
f'    "min_trades_for_mc": 50,\n'
f'    "num_mc_simulations": 1000,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 11: WALK-FORWARD ANALYSIS (WFA)\n'
f'    # ============================================================\n'
f'    # 0.80 -> first 80% IS, last 20% OOS. Set to None to disable.\n'
f'    "wfa_split_ratio": 0.80,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 12: TRADING COST SETTINGS\n'
f'    # ============================================================\n'
f'    "slippage_pct": 0.0005,\n'
f'    "commission_per_share": 0.002,\n'
f'    "risk_free_rate": 0.05,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 13: STRESS TESTING - PRICE NOISE INJECTION\n'
f'    # ============================================================\n'
f'    # 0.0 = disabled. 0.01 = +-1% uniform noise per bar.\n'
f'    "noise_injection_pct": 0.0,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 14: STRATEGY SELECTION\n'
f'    # ============================================================\n'
f'    # "all" -> run every registered strategy. Or pass a list of names.\n'
f'    "strategies": "all",\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 15: PARAMETER SENSITIVITY SWEEP\n'
f'    # ============================================================\n'
f'    "sensitivity_sweep_enabled": False,\n'
f'    "sensitivity_sweep_pct": 0.20,\n'
f'    "sensitivity_sweep_steps": 2,\n'
f'    "sensitivity_sweep_min_val": 2,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 16: ROLLING METRICS\n'
f'    # ============================================================\n'
f'    "rolling_sharpe_window": 126,\n'
f'\n'
f'    # ============================================================\n'
f'    # SECTION 17: SHORT SELLING\n'
f'    # ============================================================\n'
f'    # Hard-To-Borrow annual rate. 0.0 = disable borrow cost.\n'
f'    "htb_rate_annual": 0.02,\n'
f'}}\n'
    )

    return config_text


# ---------------------------------------------------------------------------
# In-place patcher for existing config.py
# ---------------------------------------------------------------------------

def _patch_existing_config(
    config_path: Path,
    provider: str,
    capital: float,
    start: str,
    mode: str,
    symbols_or_portfolio: object,
) -> tuple[str, list[str]]:
    """
    Patch only the wizard-collected keys in an existing config.py.

    Returns (patched_text, list_of_human_readable_changes).
    Keys not matched in the file are silently skipped so that exotic
    formatting or commented-out blocks never cause a crash.
    """
    text = config_path.read_text(encoding="utf-8")
    changes: list[str] = []

    # --- data_provider ---
    new_text, n = re.subn(
        r'("data_provider"\s*:\s*)"[^"]*"',
        rf'\1"{provider}"',
        text,
    )
    if n:
        text = new_text
        changes.append(f'data_provider → "{provider}"')

    # --- initial_capital ---
    new_text, n = re.subn(
        r'("initial_capital"\s*:\s*)[\d.]+',
        rf'\g<1>{capital}',
        text,
    )
    if n:
        text = new_text
        changes.append(f"initial_capital → {capital}")

    # --- start_date ---
    new_text, n = re.subn(
        r'("start_date"\s*:\s*)"[^"]*"',
        rf'\1"{start}"',
        text,
    )
    if n:
        text = new_text
        changes.append(f'start_date → "{start}"')

    # --- symbols_to_test / portfolios ---
    if mode == "single":
        symbols_repr = repr(symbols_or_portfolio)
        new_text, n = re.subn(
            r'("symbols_to_test"\s*:\s*)\[[^\]]*\]',
            rf'\g<1>{symbols_repr}',
            text,
        )
        if n:
            text = new_text
            changes.append(f"symbols_to_test → {symbols_repr}")
    else:
        portfolios_repr = repr(symbols_or_portfolio)
        new_text, n = re.subn(
            r'"portfolios"\s*:\s*\{[^}]*\}',
            f'"portfolios": {portfolios_repr}',
            text,
        )
        if n:
            text = new_text
            changes.append(f"portfolios → {portfolios_repr}")

    return text, changes


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run_init_wizard() -> None:
    """Interactive wizard — called when `python main.py --init` is invoked."""
    project_root = Path(__file__).resolve().parent.parent

    print()
    print(bold(cyan("  July Backtester — First-Time Setup Wizard")))
    print(cyan("  Press Ctrl-C at any time to exit without writing files."))

    # ------------------------------------------------------------------ #
    # Step 1 — Data provider                                              #
    # ------------------------------------------------------------------ #
    _section("Step 1 of 4 — Data Provider")
    print(textwrap.dedent("""\
      Available providers:
        yahoo    — free, no API key needed (default)
        csv      — load OHLCV CSV files from a local folder
        polygon  — Polygon.io REST API (free tier available)
        norgate  — Norgate Data subscription required
    """))

    provider = _ask("Which provider?", choices=["yahoo", "csv", "polygon", "norgate"], default="yahoo")

    polygon_api_key = ""
    if provider == "polygon":
        print()
        print("  Your Polygon.io API key will be written to .env (POLYGON_API_KEY=...).")
        print("  Press Enter to skip (you can add it manually later).")
        try:
            polygon_api_key = input("  Polygon API key: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            sys.exit(0)

    # ------------------------------------------------------------------ #
    # Step 2 — Capital & dates                                            #
    # ------------------------------------------------------------------ #
    _section("Step 2 of 4 — Capital & Dates")

    # initial_capital
    while True:
        raw_capital = _ask("Initial capital (USD)", default="100000")
        try:
            capital = float(raw_capital.replace(",", ""))
            if capital <= 0:
                raise ValueError
            break
        except ValueError:
            print(red("  Must be a positive number (e.g. 100000)."))

    # start_date
    while True:
        start_date = _ask("Start date (YYYY-MM-DD)", default="2010-01-01")
        try:
            datetime.strptime(start_date, "%Y-%m-%d")
            break
        except ValueError:
            print(red("  Invalid date. Use YYYY-MM-DD format."))

    # end_date — always use dynamic today expression in the written file
    end_expr = 'datetime.now().strftime("%Y-%m-%d")'
    print(f"\n  {yellow('End date')}: today (dynamic — always runs to the latest available bar)")

    # ------------------------------------------------------------------ #
    # Step 3 — What to test                                               #
    # ------------------------------------------------------------------ #
    _section("Step 3 of 4 — What to Test")
    print(textwrap.dedent("""\
      single    — one or more individual symbols (e.g. AAPL, MSFT)
      portfolio — a named basket (Nasdaq 100 JSON or custom list)
    """))

    mode = _ask("Mode?", choices=["single", "portfolio"], default="single")

    if mode == "single":
        print()
        print("  Enter one or more ticker symbols separated by commas.")
        raw_tickers = _ask("Symbols", default="SPY")
        symbols: list[str] = [t.strip().upper() for t in raw_tickers.split(",") if t.strip()]
        symbols_or_portfolio: object = symbols
    else:
        print()
        print(textwrap.dedent("""\
          Portfolio options:
            nasdaq100  — uses the bundled nasdaq_100.json file
            custom     — enter a comma-separated list of tickers
        """))
        port_choice = _ask("Portfolio type?", choices=["nasdaq100", "custom"], default="nasdaq100")

        if port_choice == "nasdaq100":
            symbols_or_portfolio = {"Nasdaq 100": "nasdaq_100.json"}
        else:
            raw_tickers = _ask("Tickers (comma-separated)", default="AAPL,MSFT,GOOGL")
            tickers: list[str] = [t.strip().upper() for t in raw_tickers.split(",") if t.strip()]
            portfolio_name = _ask("Portfolio name", default="My Portfolio")
            symbols_or_portfolio = {portfolio_name: tickers}

    # ------------------------------------------------------------------ #
    # Step 4 — Confirm & write                                            #
    # ------------------------------------------------------------------ #
    _section("Step 4 of 4 — Review & Write")

    config_path = project_root / "config.py"
    config_exists = config_path.exists()

    print(f"\n  {bold('Will write:')}")
    print(f"    {green(str(config_path))}", end="")
    if config_exists:
        print(yellow("  (existing file — wizard values will be patched in-place)"))
    else:
        print()
    if polygon_api_key:
        print(f"    {green(str(project_root / '.env'))}  (POLYGON_API_KEY)")

    print()
    if not _confirm("Proceed and write files?"):
        print(yellow("  Aborted. No files written."))
        return

    # Write or patch config.py
    if config_exists:
        patched_text, changes = _patch_existing_config(
            config_path, provider, capital, start_date, mode, symbols_or_portfolio
        )
        config_path.write_text(patched_text, encoding="utf-8")
        print(green(f"\n  Updated: {config_path}"))
        for ch in changes:
            print(f"    {cyan('→')} {ch}")
        if not changes:
            print(yellow("  (no keys matched — no changes made)"))
    else:
        config_text = _build_config(provider, capital, start_date, end_expr, mode, symbols_or_portfolio)
        config_path.write_text(config_text, encoding="utf-8")
        print(green(f"\n  Written: {config_path}"))

    # Write .env if polygon key supplied
    if polygon_api_key:
        env_path = project_root / ".env"
        marker = "POLYGON_API_KEY="
        existing = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
        if marker not in existing:
            with env_path.open("a", encoding="utf-8") as fh:
                if existing and not existing.endswith("\n"):
                    fh.write("\n")
                fh.write(f"POLYGON_API_KEY={polygon_api_key}\n")
            print(green(f"  Written: {env_path}  (POLYGON_API_KEY appended)"))
        else:
            print(yellow(f"  Skipped: {env_path}  (POLYGON_API_KEY already present)"))

    # Next steps
    print()
    print(bold("  Next steps:"))
    if config_exists:
        print(f"  1. Review {cyan('config.py')} — all other settings are unchanged.")
    else:
        print(f"  1. Review {cyan('config.py')} and adjust any other settings you need.")
    print(f"  2. Run:  {cyan('python main.py')}")
    print()
